server:
  port: 8080 # Port chạy API

spring:
  application:
    name: am-system
  
  # Cấu hình kết nối PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/ams_database # Tên database phải được tạo sẵn trong Postgres
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver

  # Cấu hình Hibernate (JPA)
  jpa:
    hibernate:
      ddl-auto: validate # CHÚ Ý: Chọn 'validate' vì chúng ta đã có sẵn file script tạo bảng. Không dùng 'update' để tránh Hibernate tự động sửa DB.
    show-sql: true # In log SQL ra console để dễ debug
    properties:
      hibernate:
        format_sql: true

  # Bật tính năng upload file Multipart (Dành cho chức năng Import Excel)
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
