server:
  port: 8080

spring:
  application:
    name: am-system

  datasource:
    url: jdbc:postgresql://localhost:5432/ams_database
    username: admin
    password: postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true 
    properties:
      hibernate:
        format-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
